### ISSUE TITLE
Account short names bug

### ISSUE THREAD

**Issue by binchik** [costflow/parser#10]
Hey costflow team!
I noticed that for an account name to be found in input text, it's enough for a word to be equal to one of `account` map keys:

https://github.com/costflow/parser/blob/master/src/transaction.ts#L36

If you have a narration (or a payee) that has an account name in it, it'll get removed.
It can be reproduced on costflow playground using this input text:
"Pay for rent 180 CNY bofa > rx + ry + food"

Double quotes fix it.

**Comment by leplay** [comment]
Thanks for reporting. I'll fix it soon.
