### ISSUE TITLE
Price auto-completion works unexpectly

### ISSUE THREAD

**Issue by kaaass** [costflow/parser#23]
Hi, thanks for the awsome repo!
I found that Costflow does not work expectly when dealing with price auto-completion. Take the example from [this passage](https://medium.com/leplay/%E4%BD%BF%E7%94%A8-costflow-%E6%8F%90%E9%AB%98-beancount-%E8%AE%B0%E8%B4%A6%E6%95%88%E7%8E%87-bdae22d1f6c4), `微信转招行 2002 wechat  > 2000 cmb + fee` are expected to get output:

```beancount
2019-11-28 * "微信转招行" #Costflow
  time: "20:18:21"
  Assets:CN:Wechat                              -2002.00 CNY
  Assets:CN:DebitCard:CMB                       +2000.00 CNY
  Expenses:Fees:Transfer                           +2.00 CNY
```

However, it actually got output like this:

```beancount
2021-09-29 * "微信转招行 wechat" #costflow
  Assets:US:BofA:Checking     -2002.00 USD
  Liabilities:CreditCard:CMB   2000.00 USD
  Assets:US:BofA:Checking      4002.00 USD
```

Tested in Playground and npm package 1.1.3. I believe the signs were not handled correctly in the calculation. Any help will be appreciated.

**Comment by leplay** [comment]
Thanks for reporting, it seems to be a bug. Let me check.

**Comment by GreenHatHG** [comment]
`49.5 eob > rx +25 ry`
![image](https://user-images.githubusercontent.com/34258355/167640483-a8678f57-d6cb-467c-9ad6-5537ccc3381e.png)

The same problem

@leplay

**Comment by leplay** [comment]
@GreenHatHG You can try `49.5 eob > 25 ry + rx` at the moment. The omitted number cannot appear in the middle in current version.
