### ISSUE TITLE
The first issue

### ISSUE THREAD

**Issue by Akuukis** [costflow/parser#7]
Hi again! :wave: My weekend challenge to transpile the code with [js2py](github.com/PiotrDabkowski/Js2Py) into Python to use it as [oneliner plugin](https://github.com/Akuukis/beancount_oneliner) v2 ultimately failed, but made plenty of stuff to salvage (#4 #5 #6).

Costflow syntax is awesome, and I'm still on my quest to create the oneliner v2 based on it. Unfortunately it means quite a big homework of splitting it into a languange agnostic spec (cucumber tests?) and typescript implementation, before getting to create a python implementation. That's big stuff, and also I have several big feedback points (e.g. error throwing) and generic questions (e.g. how's costflow hub going? I'm also doing similar stuff so perhaps unite?). Therefore better to discuss it beforehand and hence this ticket.

Are you up for a call?

**Comment by leplay** [comment]
Hi Akuukis. Thanks for the great work that you contribute to Costflow. You can send me an email (leplay@costflow.io), maybe we can continue there.

**Comment by Akuukis** [comment]
:mailbox_with_mail:
